### ISSUE TITLE
Missing Main.c file 

### ISSUE THREAD

**Issue by cclabsInc** [CoolerVoid/codewarrior#10]
/Desktop/codewarrior$ make
make: *** No rule to make target 'src/main.c', needed by 'warrior'.  Stop.

/Desktop/codewarrior$ ls src/
file_ops.c       mem_ops.c  string_ops.c       validate.c
file_ops.h       mem_ops.h  string_ops.h       validate.h
html_entities.c  routes.c   token_anti_csrf.c  whitelist.c
html_entities.h  routes.h   token_anti_csrf.h  whitelist.h

**Comment by CoolerVoid** [comment]
Pls Try to test again
git clone... https://github.com/CoolerVoid/codewarrior

cheers

**Comment by cclabsInc** [comment]
Awesome.. it works now.. Thanks!
