### ISSUE TITLE
Deal with Some loading certificate error

### ISSUE THREAD

**Issue by bincker** [CoolerVoid/codewarrior#4]
Hi  found some bugs about certificate.
default TLS checking error, comiit the code here!

https://github.com/CoolerVoid/codewarrior/compare/master...bincker:patch-1#diff-32c2ec4117fe15bd5accfa2483beb3f9
error like .
Error loading SSL cert: Invalid ssl cert

**Comment by CoolerVoid** [comment]
thank you !
fixed...
